src/resolvers/validate-arg.ts

HI. I remove this 3 lines because of them I can`t pass boolean as a parameter for the query.
E.g.:
@Query(returns => [Weight], { description: 'Get all weights' })
public async weights(@Arg('metric') metric: boolean): Promise<Weight[]> {
return await getAll(metric);
}
'''query{ weights(metric: false){name,weightId}}
With True eveything works) But with false....in this case I alwayse get undefined. 
P.S. I was convinced that nothing had changed in the tests. I also checked with my project that everything works. If there are any suspicions tell me, I'll try to find another solution to my situation.

removed lines that provide unexpected behavior for false:

---

docs/resolvers.md

The Mutation annotation updates the Mutation type, not the Query type

Docs: Mutation type in resolvers

---

docs/bootstrap.md
docs/interfaces-and-inheritance.md
docs/resolvers.md
docs/scalars.md
docs/types-and-fields.md

This improves the sentence structure in various places of the documentation.
It does not change the content, and avoids changing the already-excellent
sample code in the docs.

docs(beginners,advanced): improve grammar in several doc pages

---

CHANGELOG.md
docs/getting-started.md
docs/interfaces-and-inheritance.md
docs/resolvers.md
docs/types-and-fields.md
examples/automatic-validation/recipes-arguments.ts
examples/middlewares/recipe/recipe.args.ts
examples/resolvers-inheritance/resource/resource.resolver.ts
examples/simple-usage/recipe-resolver.ts
examples/simple-usage/schema.gql
src/decorators/types.ts
src/errors/ConflictingDefaultValuesError.ts
src/errors/index.ts
src/helpers/types.ts
src/schema/schema-generator.ts
src/schema/utils.ts
tests/functional/resolvers.ts

fix: https://github.com/19majkel94/type-graphql/issues/53
improved on: https://github.com/19majkel94/type-graphql/pull/141
I'm happy to iterate on this further if any changes are needed.

support defaultValue for input types

---

CHANGELOG.md
docs/bootstrap.md
src/index.ts
src/interfaces/index.ts
src/interfaces/resolvers-map.ts
src/utils/buildTypeDefsAndResolvers.ts
src/utils/createResolversMap.ts
src/utils/index.ts
tests/functional/typedefs-resolvers.ts

Closes #222 and allows for #135.
For #197 it needs example and a confirmation.

Add support for typeDefs and resolvers ecosystem compatibility

---

CHANGELOG.md
README.md
docs/installation.md
package-lock.json
package.json
src/errors/UnmetGraphQLPeerDependencyError.ts
src/errors/index.ts
src/schema/schema-generator.ts
src/utils/graphql-version.ts
tests/functional/peer-dependency.ts

This PR makes `graphql` and `@types/graphql` a peer dependencies. This will allow for better interop with other GraphQL ecosystem libraries without version conflict issues.
It also introduces the strict version check in runtime using [`node-semver`](https://github.com/npm/node-semver#readme) to ensure that users update the peer dependencies on TypeGraphQL update - this trick will limit all weird runtime errors that might occur when TypeGraphQL uses some new `graphql-js` features.

Make GraphQL packages peer dependencies

---

CHANGELOG.md
docs/dependency-injection.md
examples/middlewares/index.ts
examples/resolvers-inheritance/index.ts
examples/typeorm-basic-usage/index.ts
examples/typeorm-lazy-relations/index.ts
examples/using-container/index.ts
examples/using-scoped-container/index.ts
src/resolvers/create.ts
src/resolvers/helpers.ts
src/schema/build-context.ts
src/utils/container.ts
src/utils/index.ts
tests/functional/ioc-container.ts
tests/functional/resolvers.ts
tests/functional/typedefs-resolvers.ts

Right now, the only way to register a 3rd party DI container is by using the global `useContainer` function. But this global way force us to share the same container between multiple `buildSchema` calls and multiple schemas will call in runtime the same container.
This PR change this API and make the `container` to be passed as the `buildSchema` option:
```ts
import { Container } from "typedi"
import { buildSchema } from "type-graphql"
await buildSchema({
resolvers,
container: Container,
});
```
It is placed in build context like the rest of the `buildSchema` options.
This PR will allow to move toward #110 and multiple schemas support without any leaks between them.

Limit container scope to single schema

---

CHANGELOG.md
src/helpers/findType.ts
tests/helpers/circular-refs/good/CircularRef1.ts
tests/helpers/circular-refs/good/CircularRef2.ts

Tweaks the implementation of `findType` so that the return type function is called lazily rather than synchronously. This allows users to define a lazily-loaded type in that type function, and not create problematic circular dependency loops:
```ts
@Field(_type => require('./some/other/class'))
// ^ this function won't be invoked until after the module finishes loading
```

Circular dependencies fix

---

CHANGELOG.md
package.json

@19majkel94, I migrated to 0.17 and lost typescripts support at WebStorm. This pull should fix the issue.

Add types field at package.json, because we do not use default value

---

CHANGELOG.md
docs/generic-types.md
examples/generic-types/recipe.resolver.ts
src/errors/InterfaceResolveTypeError.ts
src/errors/index.ts
src/schema/schema-generator.ts
tests/functional/generic-types.ts
tests/functional/interfaces-and-inheritance.ts

Pretty dirty solution but should be enough as a temporary fix until #183 will be achieved 💪 
Closing #160 🔒

fix(inheritance): allow for returning plain objects

---

CHANGELOG.md
docs/types-and-fields.md
src/helpers/types.ts
src/schema/build-context.ts
src/schema/schema-generator.ts
tests/functional/default-nullable.ts

Add support for setting default nullability for fields and return types

---

CHANGELOG.md
docs/subscriptions.md
src/decorators/Subscription.ts
src/metadata/definitions/resolver-metadata.ts
src/schema/schema-generator.ts
src/utils/types.ts
tests/functional/subscriptions.ts

As described in #327, this PR adds a `subscribe` option to the `Subscription` decorator. This option allows it to use custom subscription systems, e.g. the one Prisma is providing.

Add `subscribe` option to `Subscription` decorator

---

docs/generic-types.md

docs(generic-types): correct syntax error in example

---

CHANGELOG.md
docs/faq.md
docs/types-and-fields.md
src/decorators/types.ts
src/helpers/findType.ts
src/helpers/types.ts
tests/functional/fields.ts

Allow generating nested lists of scalars and object types, such as `[[Int]]`, or `[[CustomObject]]` with mongo like syntax.
```typescript
@ObjectType()
class TestObject {
// Will become [[String!]!]!
@Field(type => [[String]])
NestedArrayField: string[][];
// Will become [[String!]!]
@Field(type => [[String]], { nullable: true })
nullableNestedArrayField: string[][] | null;
// Will become [[String]]!
@Field(type => [[String]], { nullable: "items" })
nonNullNestedArrayWithNullableItemField: Array<Array<String | null> | null>;
// Will become [[String]]
@Field(type => [[String]], { nullable: "itemsAndList" })
nestedArrayWithNullableItemField: Array<Array<String | null> | null> | null;
}
```
closes #277

feat(fields): add support for nested arrays

---

docs/installation.md

In the beginners guide: "installation", it says you need to install @types/graphql. After installing it says: `npm WARN deprecated @types/graphql@14.5.0: This is a stub types definition. graphql provides its own type definitions, so you do not need this installed.`

@types/graphql is included with graphql

---

CHANGELOG.md
docs/complexity.md
examples/query-complexity/index.ts
package-lock.json
package.json
src/schema/schema-generator.ts
tests/functional/resolvers.ts

https://github.com/slicknode/graphql-query-complexity/issues/19

Upgrade `graphql-query-complexity` dependency and related code

---

docs/dependency-injection.md

Added example:
- add an example in the 'Dependency injection' page that shows the proper way to bind a resolver class if InversifyJS is being used.
The reason I've done this is because I had some trouble to get it working, it wasn't easy to gather information about Inversify and GraphQL, I tried different approaches and that's the only one that worked for me.

docs(container): add InversifyJS side note

---

CHANGELOG.md
docs/validation.md
src/helpers/types.ts
src/resolvers/convert-args.ts
src/resolvers/helpers.ts
src/resolvers/validate-arg.ts
src/schema/schema-generator.ts
tests/functional/resolvers.ts
tests/functional/validation.ts

Fix transforming and validating nested inputs and arrays

---

CHANGELOG.md
docs/emit-schema.md
examples/generic-types/schema.gql
examples/interfaces-inheritance/schema.gql
examples/mixin-classes/schema.gql
examples/simple-usage/schema.gql
examples/typegoose/schema.gql
src/utils/buildSchema.ts
src/utils/emitSchemaDefinitionFile.ts
src/utils/index.ts
tests/functional/emit-schema-sdl.ts

This PR aims to solve issues #379, #442 and #417.
However because the `lexicographicSortSchema` utility strips off all additional properties from types config, the schema sorting only applies to the emitted schema SDL file for now, on the contrary to @mattiassundling fork: https://github.com/mattiassundling/type-graphql/commit/5a6fbc6e4aeb97a3dd78a3d2a09982109b69ce58
So if you need a sorted schema in GraphQL Playground or other tools that uses introspection and if you don't rely on the putting metadata in the type config, you should use `lexicographicSortSchema` on your own, e.g.:
```ts
transformSchema: (schema: GraphQLSchema) => lexicographicSortSchema(schema)
```

Sort emitted schema SDL file

---

CHANGELOG.md
src/metadata/metadata-storage.ts
src/metadata/utils.ts
tests/functional/metadata-storage.ts

This is an attempt to at least partially solve what I believe is a memory leak issue regarding metadata-storage. 
If you're using a workflow where you build the schema dynamically on every request the `queries` and `mutations` arrays that are properties of the global metadata storage instance quickly grow in size for classes utilizing inheritance. From what I can tell it filters for the objects it's looking for in order to copy and modify metadata from the parent resolver class but creates new entries and adds them to an ever growing list. This solution simply modifies those object in place relying on pass by reference so that the array doesn't grow forever and cause memory issues as well as degraded performance on each subsequent request.
In my workflow simply clearing the global …

Fix duplicated entries for resolver classes that use inheritance

---

docs/bootstrap.md
website/versioned_docs/version-0.17.1/bootstrap.md

Adding a note that the examples indicate .ts files for the resolver paths, but once the files are compiled (ie in production environments), the paths will be .js not .ts files.

Update bootstrap docs

---

docs/types-and-fields.md

It isn't clear from the docs that "items" and "itemsAndList" option are passed as strings.

Improves clarity

---

CHANGELOG.md
src/schema/schema-generator.ts
tests/functional/interfaces-and-inheritance.ts

Fixes #566 
New to this codebase, open to feedback!
~~As an aside, the [`defaultFieldResolver` function](https://github.com/graphql/graphql-js/blob/fe878eef98aba23df988e858dbafa029d6351bd1/src/execution/execute.js#L1187) just does the _check if this is a function, if so, call it, otherwise return it as is_ thing.~~
**Edit:** I changed to use the `createBasicFieldResolver` function. It looks like it could also be extended to the advanced resolver type to support external interface resolvers? Also, I think that the status quo (before this PR) wouldn't apply any auth checking to fields defined on interfaces since it doesn't run any middlewares.

Fix interface resolvers with custom schemaName

---

CHANGELOG.md
src/resolvers/create.ts
src/schema/schema-generator.ts
tests/functional/subscriptions.ts

This PR adds proper `authChecker` call for subscriptions.
Now auth is also checked during subscribe phase to reject unauthorized clients, not only when pubsub emit new event in selected topic (when subscription method body is called). 
Closes #175 🔒

Fix `@Authorized` in subscriptions 

---

CHANGELOG.md
docs/bootstrap.md
docs/interfaces.md
src/decorators/InterfaceType.ts
src/metadata/definitions/interface-class-metadata.ts
src/schema/schema-generator.ts
tests/functional/generic-types.ts
tests/functional/interfaces-and-inheritance.ts
tests/helpers/getSchemaInfo.ts

This PR adds a feature that automatically emit in schema all the object types that implements the interface types referenced in schema definition.
It also adds an option to disable the auto register feature per interface type, like the `Node` interface case for Relay-based system, in case of multiple schemas isolation.
Closes #568

Automatically register object types implementing used interface type

---

examples/3-nest-js/package-lock.json
examples/3-nest-js/package.json

Hey @MichalLytek, thanks for your work on TypeGraphQL, this new version looks super promising combined with Prisma!
When testing the NestJS example I ran into an error:
```
$ ts-node --transpile-only ./index.ts
Error: Cannot find module 'rxjs'
Require stack:
- /Users/beeman/kikstart/scratch/type-graphql/examples/3-nest-js/node_modules/@nestjs/common/cache/interceptors/cache.interceptor.js
- /Users/beeman/kikstart/scratch/type-graphql/examples/3-nest-js/node_modules/@nestjs/common/cache/interceptors/index.js
- /Users/beeman/kikstart/scratch/type-graphql/examples/3-nest-js/node_modules/@nestjs/common/cache/index.js
- /Users/beeman/kikstart/scratch/type-graphql/examples/3-nest-js/node_modules/@nestjs/common/index.js
- /Users/beeman/kikstart/scratch/type-graphql/examples/3-nest-js/node_modules …
```

fix: add RxJS dependency to NestJS demo

---

CHANGELOG.md
src/schema/utils.ts
tests/functional/directives.ts

For Example:
```typescript
@ObjectType({ isAbstract: true })
class INode {
@Field(() => ID)
id!: string
@Directive('@formatDate')
@Field(() => Timestamp)
createdAt: Date;
@Directive('@formatDate')
@Field(() => Timestamp)
updatedAt: Date;
}
//  People class cannot extends INode Filed directives  
@ObjectType()
class People extends INode {
}
```

fix(schema): Fix directives cannot be extends

---

docs/browser-usage.md

I've had to do the same browser shim in cypress because I am using a module which exports the type-graphql decorators. This PR adds that info to the docs.

Add info about shim for cypress

---

docs/scalars.md

https://typegraphql.com/docs/scalars.html#date-scalars
> They are exported from the type-graphql package as GraphQLISODateScalar and GraphQLTimestampScalar.
The GraphQL scalar types are exported as the following:

docs: fix date scalar export names

---

website/pages/en/index.js

Change the typegoose link in `Interoperable` to the new maintained Repository

docs: Change Typegoose link to new Repository

---

CONTRIBUTING.md
README.md

Expand the contributing guidelines into their own dedicated documentation section, to help streamline and guide future contributions.
Closes #682.

docs: add initial contributing docs

---

CHANGELOG.md
src/errors/CannotDetermineGraphQLTypeError.ts
tests/functional/resolvers.ts

The existing error message was slightly confusing to me. It caused me to re-read the message several times to understand it.
I felt like a slight change in wording could improve the readability.

fix: Confusing error wording

---

website/pages/snippets/testability.md

Found a typo. The rate repository is called *rateRepository* in the constructor however is used as *ratingsRepository* in ratings function.

Found a typo in repository name

---

CHANGELOG.md
src/schema/schema-generator.ts
tests/functional/interfaces-and-inheritance.ts
tests/functional/unions.ts

fix(interfaces-unions): handle resolveType returning undefined

---

docs/subscriptions.md

This PR fixes the docs for the function arguments of the `subscribe` option (as per the `ResolverFn` [signature](https://github.com/apollographql/graphql-subscriptions/blob/master/src/with-filter.ts#L4)).

docs(subscriptions): fix arguments of the `subscribe` option

---

CHANGELOG.md
src/schema/schema-generator.ts
tests/functional/interfaces-and-inheritance.ts

Fix not registering object types when interface type is used as object type field type

---

CHANGELOG.md
src/resolvers/convert-args.ts
tests/functional/resolvers.ts

Properly transform nested array of input type classes

---

docs/interfaces.md

Typo.
The GraphQL interface should be Person and not IPerson.

Typo: GraphQL IPerson -> GraphQL Person

---

CHANGELOG.md
docs/directives.md
src/schema/definition-node.ts
src/schema/schema-generator.ts
tests/functional/directives.ts
tests/helpers/directives/assertValidDirective.ts

This PR adds support for using `@Directive` on InterfaceType (and its fields).
Directives are supported on interface as per [GraphQL specs](https://spec.graphql.org/June2018/#sec-Interfaces) and that support is widely implemented, see [Apollo](https://github.com/graphql/graphql-js/blob/a62eea88d5844a3bd9725c0f3c30950a78727f3e/src/language/directiveLocation.js#L22-L33) for example.
In this proposed implementation, any ObjectType implementing the interface (more precisely, whose typescript class extends the typescript class of the interface) will inherit its directives. This seems in line with the current behavior of TypeGraphQL.
Nevertheless, as it stands, users would **not** be able to __only__ add directive to the interface and not the objects implementing it.
I'd love insights about …

Add directives support to Interfaces

---

CHANGELOG.md
src/decorators/Arg.ts
src/metadata/definitions/param-metadata.ts
src/schema/schema-generator.ts
tests/functional/deprecation.ts

Allow deprecating input fields and arguments

---

CHANGELOG.md
src/decorators/Authorized.ts
src/helpers/decorators.ts
tests/functional/authorization.ts

The `@Authorized` decorator specifies `roles: T[]` or `...roles: T[]` as its argument. 
We have a constant sets of roles:
```ts
export const ADMIN_ROLES = ['a', 'b', 'c'] as const;
export const AdminRole = typeof ADMIN_ROLES[number];
```
We would like to use:
```ts
@Authorized<AdminRole>(ADMIN_ROLES);
```
TypeScript doesn't allow this because `readonly` arrays cannot be used in places where a non-`readonly` array is specified. However, a normal `Array` _can_ be used anywhere a `readonly Array<T>` is specified.
For now our workaround is spreading our constant array when used.
```ts
@Authorized(...ADMIN_ROLES);
```

Support readonly arrays for roles of Authorized decorator

---

CHANGELOG.md
src/resolvers/validate-arg.ts
tests/functional/validation.ts

Fixes https://github.com/MichalLytek/type-graphql/issues/1328.

Fix validation failing for nullable lists

---

.github/workflows/check.yml
.github/workflows/license.yml
.github/workflows/release.yml
.github/workflows/website.yml

- Fixed workflows that depends on another workflow
- `actions/checkout` always clone the corresponding `ref` to avoid clashes with `master`
- Cancel parallel workflows (`concurrency`) if the corresponding workflow must be run uniquely (e.g. `release` and `license`)

fix:(ci): workflows that depends on another workflow

---

src/utils/createResolversMap.ts
tests/functional/typedefs-resolvers.ts

This PR fixes the issue mentioned [here](https://github.com/MichalLytek/type-graphql/issues/1142) with tests as mentioned [here](https://github.com/MichalLytek/type-graphql/issues/1142#issuecomment-997357073).
The tests successfully fail when the `startsWith` is replaced back with `includes`.
(Edit: The second 'here' is supposed to link to the last comment of the mentioned issue but it's not scrolling.)

fix(resolvers): resolve #1142 name issue and add relevant tests

---

.npmrc
package.json

This PR should be merged only after PR #1610 is merged
Node.js 16 reached EOL (see https://nodejs.org/en/blog/announcements/nodejs16-eol) on September 11th, 2023

build: remove support for node 16

---

CHANGELOG.md
src/metadata/metadata-storage.ts
src/schema/schema-generator.ts
tests/functional/generic-types.ts
tests/functional/resolvers.ts

This PR is another approach (after #1691 by community) to fix an issue related to subsequent schema builds, especially when we have resolvers with inheritance and those resolvers queries/mutations contains args.
The approach to fix this was to just block subsequent metadata storage `.build()` actions, which were mutating the initial metadata storage values.
Fixes #1321 🚀

fix(schema): prevent issues with subsequent schema builds

---

docs/subscriptions.md

Typegraphql doesn't provide PubSub decorator. it provide only an interface. The code example should call pubSub instance created before to publish a notification.

docs: fix pubSub.publish code example
