MichalLytek/type-graphql

- CHANGELOG.md
- dev.js
- docs/authorization.md
- examples/06-authorization/auth-checker.ts
- examples/06-authorization/context.interface.ts
- examples/06-authorization/examples.gql
- examples/06-authorization/index.ts
- examples/06-authorization/recipe.type.ts
- examples/06-authorization/resolver.ts
- examples/06-authorization/sample-recipes.ts
- examples/06-authorization/user.interface.ts
- src/decorators/Authorized.ts
- src/decorators/index.ts
- src/errors/ForbiddenError.ts
- src/errors/UnauthorizedError.ts
- src/errors/helpers/formatArgumentValidationError.ts
- src/errors/index.ts
- src/index.ts
- src/metadata/definition-interfaces.ts
- src/metadata/metadata-storage.ts
- src/resolvers/create.ts
- src/resolvers/helpers.ts
- src/schema/build-context.ts
- src/schema/schema-generator.ts
- src/types/auth-checker.ts
- src/types/resolvers.ts
- tests/functional/authorization.ts
> Authorization guards feature

- README.md
Thanks for the great work man. I cleaned up the grammar a bit in your readme.
> Update Grammar in Readme.md

- CHANGELOG.md
- docs/subscriptions.md
- examples/simple-subscriptions/examples.gql
- examples/simple-subscriptions/resolver.ts
- src/decorators/Subscription.ts
- src/decorators/types.ts
- src/interfaces/ResolverFilterData.ts
- src/interfaces/ResolverTopicData.ts
- src/interfaces/index.ts
- src/metadata/definitions/resolver-metadata.ts
- src/schema/schema-generator.ts
- tests/functional/subscriptions.ts
> subscribe to dynamic topics

- docs/interfaces-and-inheritance.md
See #125 for an example of the confusion
> Clarify object type inheritance docs

- docs/types-and-fields.md
> Fix "definition" Typo

- docs/introduction.md
Hi - Sorry if I'm not doing this correctly.  I'm trying to help out with documentation as part of Hacktoberfest and I'm a newbie.  I hope the edits/suggestions are useful and make your documentation more clear.  Happy to look at/edit more!
> Grammatical edits

- docs/interfaces-and-inheritance.md
also splits a long sentence into two
> fixes a typo

- docs/emit-schema.md
Just wanted to add some minor grammar fixes that makes the text more fluent and easier to read.
> Some grammar corrections

- docs/resolvers.md
Added `import` statements to the markdown code
NB: nice project BTW! It saved me like LOOOOOOOT of time 😄
> Updated resolver documentation page

- docs/middlewares.md
Found this little typo, I believe it should be called 'Authorized' as in 'Authorization'.
> Fix '@Autorized' typo

- docs/complexity.md
> Minor whitespace fixes in complexity.md

- docs/getting-started.md
@benawad did awesome work there, it would make sense to link it
> adds a link to Ben Awads youtube video series

- docs/resolvers.md
Getters to make helper fields work, from issue https://github.com/MichalLytek/type-graphql/issues/420
> docs(resolvers): fix argument helpers props syntax

- docs/browser-usage.md
- gulpfile.ts
- src/browser-shim.ts
This PR adds TS-compatible browser shim that is required for Angular's project with AOT enabled.
It also fixes compatibility with ES5 environment.
Closes #469, #350.
> Upgraded browser shim

- docs/getting-started.md
- website/versioned_docs/version-0.17.2/getting-started.md
Fixes https://github.com/MichalLytek/type-graphql/issues/501
> Fix getting-started errors

- .github/ISSUE_TEMPLATE/bug_report.md
`Envrionment -> Environment`
Also made other consistency tweaks for the section titles. :^)
> Fix bug report typo

- docs/complexity.md
- examples/query-complexity/index.ts
- website/versioned_docs/version-0.17.5/complexity.md
- website/versioned_docs/version-1.0.0-rc.1/complexity.md
I think it would make more sense to remove the `=` so it doesn't throw at 20 with "it is over 20"
> docs: fix logic of complexity error statement

- examples/typegoose/entities/recipe.ts
- examples/typegoose/index.ts
Hope this is ok. 
Refers to this: https://github.com/MichalLytek/type-graphql/issues/117#issuecomment-645810830
Scott
> Changes arrayProp to prop as arrayProp is deprecated

- CHANGELOG.md
- docs/enums.md
- src/decorators/enums.ts
- src/decorators/types.ts
- src/metadata/definitions/enum-metadata.ts
- src/schema/schema-generator.ts
- tests/functional/enums.ts
> Support for enums with descriptions and depreciations

- CHANGELOG.md
- src/helpers/findType.ts
- tests/functional/manual-decorators.ts
> Prevent crashing when reflected type is undefined

- docs/resolvers.md
Here is the huge pull request 😄
> docs(resolvers): fix wrong params order in snippet

- src/metadata/metadata-storage.ts
> removes TODO comment since it is no longer valid

- docs/directives.md
Adding a ref to existing documentation to print schema with directives
> docs(directives): add link to emit schema with directives

- .github/workflows/ci.yml
Support prerelease semver in CI
RegEx is copied from the [official one](https://semver.org/#is-there-a-suggested-regular-expression-regex-to-check-a-semver-string)
> chore(ci): support semver prerelease

- .github/workflows/ci.yml
> chore(ci): update release-changelog-builder-action

- .github/workflows/license.yml
Automatically update (creates a PR) year range in `LICENSE` on `1st january at 00:00`
> chore(ci/license): license github action

- examples/apollo-cache/cache-control.ts
I used the CacheControl directive in my project, but it didn't allow me to set maxAge to 0.
> Apollo Cache example: Allow maxAge to be 0

- docs/browser-usage.md
[Updated layout since the PR before was not consistent] Since Next.js is quite popular and it took me some time to figure this out, this might be helpful for others
> Add Next.js browser shim and update headers/format

- docs/subscriptions.md
The package name is here: https://www.npmjs.com/package/@graphql-yoga/subscription
> docs: fix @graphql-yoga/subscription package name

- .github/configs/codeql.yml
- .github/workflows/codeql.yml
- Use [security-and-quality](https://docs.github.com/en/code-security/code-scanning/creating-an-advanced-setup-for-code-scanning/customizing-your-advanced-setup-for-code-scanning#using-queries-in-ql-packs) queries
- Inline configuration
> chore(ci): codeql security-and-quality and inline config
